site_name: The Axiom Engine
site_description: A philosophical framework for ethical governance based on Truth, Wisdom, and Humanity
site_url: https://axiomengine.org
repo_url: https://github.com/XvsMetroid/singularity
repo_name: XvsMetroid/singularity

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

docs_dir: docs_content

plugins:
  - search
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: README.md
  - Core Framework:
    - Constitution: 01_CORE/00_The_Constitution.md
    - Genesis & Methodology: 01_CORE/01_The_Genesis_and_Cognitive_Methodology.md
    - Saying Log: 01_CORE/02_The_Saying_Log.md
    - Glossary: 01_CORE/03_Glossary_of_Terms.md
    - Core Metaphors: 01_CORE/04_Core_Metaphors.md
    - Framework Blueprint: 01_CORE/framework-as-blueprint.md
  - Getting Started:
    - Onboarding: 05_RESOURCES/ONBOARDING.md
    - FAQ: 05_RESOURCES/FAQ.md
    - Simple Guides:
      - The Triad: 05_RESOURCES/Simple_Guides/the-triad.md
      - Feedback Loop: 05_RESOURCES/Simple_Guides/feedback-loop.md
      - Meta Monitor: 05_RESOURCES/Simple_Guides/meta-monitor.md
  - Research:
    - Published Articles:
      - Overview: 04_RESEARCH/Published_Articles/the-axiom-engine-philosophical-overview.md
      - Sovereign Triad: 04_RESEARCH/Published_Articles/the-sovereign-triad-a-philosophical.md
      - Briefing: 04_RESEARCH/Published_Articles/the-sovereign-triad-briefing.md
      - 5 Revelations: 04_RESEARCH/Published_Articles/how-to-fix-a-broken-world-5-revelations.md
      - Analysis: 04_RESEARCH/Published_Articles/analysis-of-sovereign-triad.md
    - Explorations:
      - Compass for Life: 04_RESEARCH/Explorations/a-compass-for-life-an-introduction.md
      - Anti-Entropy: 04_RESEARCH/Explorations/the-anti-entropy-axiom-engine.md
      - Cognitive Methods: 04_RESEARCH/Explorations/cognitive-methodologies.md
  - Applications:
    - Proposals:
      - AI Ethics Charter: proposals/P-01_AI_Ethics_Charter.md
      - Constitutional Reform: proposals/P-02_Constitutional_Reform_Framework.md
      - Global Governance: proposals/P-03_Global_Governance_Model.md
      - Organizational Design: proposals/P-04_Organizational_Design_Template.md
      - Pilot Methodology: proposals/P-05_Pilot_Program_Methodology.md
    - Case Studies:
      - Historical: case-studies/historical/CS-H-01_Historical_Entropy_and_Antithesis.md
      - Contemporary: case-studies/contemporary/CS-C-01_Simulated_Project_Challenge.md
  - Community:
    - Overview: 06_COMMUNITY/README.md
    - RFC Process: 06_COMMUNITY/RFC/README.md
    - Current RFCs: 06_COMMUNITY/RFC/001_Measurement_Problem.md
  - Documentation:
    - Index: docs/index.md
    - AI Guide: docs/AI-guide.md
    - Contributing: CONTRIBUTING.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/XvsMetroid/singularity
  tags:
    philosophy: philosophy
    triad: triad
    truth: truth
    wisdom: wisdom
    humanity: humanity